'use client'
import React from 'react';

import { Roboto } from 'next/font/google'
import { globalStyles } from "@/styles/global";
import logoImg from '../assets/logo.svg'
import { StyledContainer, StyledHeader } from "@/styles/pages/app";

import Image from 'next/image'
import * as Dialog from '@radix-ui/react-dialog';
import SideDrawer from "@/app/components/SideDrawer";
import OpenCartButton from './components/OpenCartButton';

globalStyles();

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
})

// const roboto = localFont({
//   src: "./fonts/Roboto-Regular.ttf",
//   variable: "--font-roboto",
//   weight: "400",
// });

// const robotoBold = localFont({
//   src: "./fonts/Roboto-Bold.ttf",
//   variable: "--font-roboto-bold",
//   weight: "700",
// });


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
       <head>
      </head>
      <body className={roboto.className}>
        <Dialog.Root>
          <StyledContainer>
              <StyledHeader>
                <Image src={logoImg} alt="" />
                <OpenCartButton/>
              </StyledHeader>
              <SideDrawer />       
        
            {children}
          </StyledContainer>
        </Dialog.Root>
      </body>  
    </html>
  );
}
